### ISSUE TITLE
2.6 Autograd 中代码笔误

### ISSUE THREAD

**Issue by cnkeysky** [TingsongYu/PyTorch-Tutorial-2nd#10]
- 案例4：手动实现2D卷积
![image](https://github.com/TingsongYu/PyTorch-Tutorial-2nd/assets/32216693/8874f0e0-7308-43b7-873c-2c468b1fc5d2)
应将 `MyConv2D` 修改为 `Conv2D`

**Comment by TingsongYu** [comment]
感谢指正，已修改，并且添加了相关注释。[2.6-autograd](https://github.com/TingsongYu/PyTorch-Tutorial-2nd/blob/main/code/chapter-2/06_autograd.ipynb)
