### ISSUE TITLE
2.5 计算图中对Node和Edge的解释有误

### ISSUE THREAD

**Issue by cnkeysky** [TingsongYu/PyTorch-Tutorial-2nd#11]
![image](https://github.com/TingsongYu/PyTorch-Tutorial-2nd/assets/32216693/c84b3424-30bd-4326-b50a-b48dabcaf9f0)
[pytorch官方文档给出的定义](https://pytorch.org/docs/stable/export.ir_spec.html#node)
![image](https://github.com/TingsongYu/PyTorch-Tutorial-2nd/assets/32216693/ffcdacbe-0451-4dea-96f8-7eb4aa4fe405)
解释互换比较合适。

**Comment by TingsongYu** [comment]
确实理解有误，感谢指正，已更新。[2.5-computational-graphs](https://tingsongyu.github.io/PyTorch-Tutorial-2nd/chapter-2/2.5-computational-graphs.html) 查了一下资料，解释还不能互换，边的概念仅为数据流向。节点包括了数据和运算操作，如标量、向量、矩阵、加、减、乘、除等。
![image](https://github.com/TingsongYu/PyTorch-Tutorial-2nd/assets/19504755/d4733fb6-ba66-4ba3-a257-c367e64f71c1)
