### ISSUE TITLE
pytorch官方文档是？

### ISSUE THREAD

**Issue by A-Pai** [TingsongYu/PyTorch-Tutorial-2nd#12]
pytorch官方文档是这个？
https://pytorch.org/docs/stable/index.html
感觉不详细，比如detach的用法
当前遇到这样的问题，找不到权威的帮助   https://ask.csdn.net/questions/8116547?weChatOA=weChatOA1
不知道是何原因，可否请版主帮忙解答

**Comment by Reid-Cui7** [comment]
> pytorch官方文档是这个？ https://pytorch.org/docs/stable/index.html 感觉不详细，比如detach的用法 当前遇到这样的问题，找不到权威的帮助 https://ask.csdn.net/questions/8116547?weChatOA=weChatOA1 不知道是何原因，可否请版主帮忙解答

detach只是将其从当前计算图中移除，detach返回的新Tensor不计算梯度。但返回的这个Tensor与原来的共享内存，你链接里修改了返回的Tensor，当然out也会改变。
官方文档是最清楚的了https://pytorch.org/docs/stable/generated/torch.Tensor.detach.html#torch.Tensor.detach
tf的官方文档除外

**Comment by A-Pai** [comment]
我说的不是“out也会改变”的问题，而是 https://blog.csdn.net/qq_43489708/article/details/125154444 中说的“当使用detach()分离tensor并且更改这个tensor时，即使再对原来的out求导数，会影响backward()，会出现错误”，我就是这样做的，但是没有报错

**Comment by Reid-Cui7** [comment]
> 我说的不是“out也会改变”的问题，而是 https://blog.csdn.net/qq_43489708/article/details/125154444 中说的“当使用detach()分离tensor并且更改这个tensor时，即使再对原来的out求导数，会影响backward()，会出现错误”，我就是这样做的，但是没有报错

因为你举得例子当中，计算梯度的时候并没有用到out的值，你贴的那个例子中，参与梯度计算的一个变量被原地修改了，所以就提示错误了。可以简单理解为，在链式法则中，你修改的变量参不参与计算。比如你自己的那个例子，a是参与梯度计算的，如果你原地修改a就会得到相同的报错。而且那个帖子本身写的就有问题，准确的是如果你原地修改的变量参与梯度计算，那么就会报错

**Comment by A-Pai** [comment]
https://blog.csdn.net/qq_43489708/article/details/125154444 的问题在何处？

**Comment by Reid-Cui7** [comment]
> https://blog.csdn.net/qq_43489708/article/details/125154444 的问题在何处？

不就是他误导你那句吗？那句话不严谨啊，他要是写的清楚，你也不能又发个帖子讨论报错不报错的问题
