### ISSUE TITLE
2.5 git图的名称有误

### ISSUE THREAD

**Issue by thunderbolt-fire** [TingsongYu/PyTorch-Tutorial-2nd#15]
> 图1为pytorch的静态图示意，图2为TensorFlow的静态图示意。

是否应该为pytorch的动态图示意

**Comment by TingsongYu** [comment]
是的，打错了。已经改为“图1为pytorch的动态图示意”
https://tingsongyu.github.io/PyTorch-Tutorial-2nd/chapter-2/2.5-computational-graphs.html
