### ISSUE TITLE
pytorch 2.0的介绍，建议加入

### ISSUE THREAD

**Issue by hao203** [TingsongYu/PyTorch-Tutorial-2nd#16]
pytorch 2.0以上版本已经发布很久课，我看到pytorch安装的章节还写的都是1.*版本介绍，
建议加入2.0的介绍，其与1.*版本有什么不同，也稍微介绍下。

**Comment by TingsongYu** [comment]
的确，pytorch2.0是需要介绍一下，7月初安排！

**Comment by TingsongYu** [comment]
已增加 pytorch 2.0 介绍及torch.compile 实验 。https://tingsongyu.github.io/PyTorch-Tutorial-2nd/chapter-1/1.7-PyTorch2.0.html

**Comment by hao203** [comment]
Thanks
