### ISSUE TITLE
可以多讲讲在vscode中打开jupyter notebook

### ISSUE THREAD

**Issue by A-Pai** [TingsongYu/PyTorch-Tutorial-2nd#17]
“1.6 环境配置之Jupyter Notebook”--我觉得可以多讲讲在vscode中打开jupyter notebook，比 浏览器的好用，可以逐行运行和看变量

**Comment by TingsongYu** [comment]
vscode工具的使用，可以添加vscode使用链接介绍好了，就不在pytorch的书籍中展开啦。感谢建议。
