### ISSUE TITLE
显示有误

### ISSUE THREAD

**Issue by A-Pai** [TingsongYu/PyTorch-Tutorial-2nd#18]
https://tingsongyu.github.io/PyTorch-Tutorial-2nd/chapter-2/2.5-computational-graphs.html#25-%E8%AE%A1%E7%AE%97%E5%9B%BE
![image](https://github.com/TingsongYu/PyTorch-Tutorial-2nd/assets/5112397/66eae080-bb4f-44be-8ec0-695e9fc8d13e)

**Comment by TingsongYu** [comment]
关于节点和边的定义描述是经过修改，所以这块特地用了删除线。由于以前对节点、边的描述与现在官方文档的描述有冲突，并且经过多方资料查找仍然存在两种描述。综合考虑，还是保留旧的描述，用删除线表示。具体参考#11 https://github.com/TingsongYu/PyTorch-Tutorial-2nd/issues/11

**Comment by A-Pai** [comment]
您的邮件我已收到  I have received your email                        李刚  LI,Gang
