### ISSUE TITLE
程序有误？运行报错

### ISSUE THREAD

**Issue by A-Pai** [TingsongYu/PyTorch-Tutorial-2nd#19]
https://tingsongyu.github.io/PyTorch-Tutorial-2nd/chapter-2/2.6-autograd.html

![image](https://github.com/TingsongYu/PyTorch-Tutorial-2nd/assets/5112397/932d6a11-29ae-42ee-a315-3d1dea216178)

应该为“MyConv2D”？

**Comment by TingsongYu** [comment]
是的，书中代码有误。在代码中已经修改过了。多谢提醒。
![image](https://github.com/TingsongYu/PyTorch-Tutorial-2nd/assets/19504755/072e4698-d4d7-446e-aeb8-30244e550736)
https://github.com/TingsongYu/PyTorch-Tutorial-2nd/blob/main/code/chapter-2/06_autograd.ipynb
