### ISSUE TITLE
pdf版本

### ISSUE THREAD

**Issue by HongJunShan** [TingsongYu/PyTorch-Tutorial-2nd#2]
谢谢作者的无私奉献，请问pdf版本的有吗？

**Comment by TingsongYu** [comment]
感谢关注。已经将PDF版本通过[release](https://github.com/TingsongYu/PyTorch-Tutorial-2nd/releases/tag/v1.0.0)发布了，可下载，或者通过百度网盘下载.
网盘链接：https://pan.baidu.com/s/1trkq6Vr2DBPNXpRwK_Jdzg    
提取码：4w15
