### ISSUE TITLE
图象处理案例，肺炎分割的train

### ISSUE THREAD

**Issue by WanderJN** [TingsongYu/PyTorch-Tutorial-2nd#22]
train_transform = A.Compose([
        A.Resize(width=PATCH_SIZE, height=PATCH_SIZE),
        A.HorizontalFlip(p=0.5),
        A.VerticalFlip(p=0.5),
        A.RandomRotate90(p=0.5),
        A.Transpose(p=0.5),
        A.ShiftScaleRotate(shift_limit=0.01, scale_limit=0.04, rotate_limit=0, p=0.25),
        A.Normalize(norm_mean, norm_std, max_pixel_value=255.),
        ToTensorV2(),
    ])
这个变换总是报错：ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().

**Comment by TingsongYu** [comment]
应该是albumentations版本问题，用的是哪个版本？这边测试的时候是 albumentations                    1.3.0

**Comment by WanderJN** [comment]
非常感谢您的回复，您这本书写的特别好，很系统也清晰易懂，案例的代码也很优美。
我最后在dataset构建里把ToTensorV2()单独封装到A.Compose里。相当于transform了两次，然后没再报错 解决了！

**Comment by TingsongYu** [comment]
应该是ToTensorV2()出的问题，可以参考https://github.com/albumentations-team/albumentations/pull/609

**Comment by TingsongYu** [comment]
感谢认可，哈哈哈。 解决就好
![image](https://github.com/TingsongYu/PyTorch-Tutorial-2nd/assets/19504755/a3a6b296-4a1c-4d83-a8db-163746079f1f)

**Comment by WanderJN** [comment]
谢谢谢谢！受益颇丰！
