### ISSUE TITLE
公式无法显示

### ISSUE THREAD

**Issue by hanruiyao163** [TingsongYu/PyTorch-Tutorial-2nd#23]
2.6节的公式显示原始代码，不能显示正常公式
![image](https://github.com/user-attachments/assets/72abfbb7-b2e5-49e3-a993-110bd47f2a59)

**Comment by TingsongYu** [comment]
谢谢提醒，已更新格式。这个需要gitbook新增一个插件“katex”才可以显示公式
![image](https://github.com/user-attachments/assets/174231d4-a4ed-4aa0-8998-95886a701188)
