### ISSUE TITLE
Pytorch教程第二版，书中224页关于MIOU计算，与代码不一致

### ISSUE THREAD

**Issue by WanderJN** [TingsongYu/PyTorch-Tutorial-2nd#24]
作者您好，书中224页关于MIOU计算的macro和macro-imagewise参数的解释和实际代码运行结果图片不一致，而且与您GitHub上上传代码描述也不一致，请您检查一下是否有误，谢谢了。
您前边说的是“在这里重点讲一下，本案例采用的是macro来统计，因此iou比较低”，后边代码展示里使用“macro”对阴性图片的MIOU反而为1.

**Comment by TingsongYu** [comment]
是的， 在文中提到采用reduction="macro"来计算，但在上传的代码中采用了reduction="macro-imagewise"。 
两种设置在代码中都出现了，可以分别开启124行和125行代码，观察两种的差异。
[utils.py](https://github.com/TingsongYu/PyTorch-Tutorial-2nd/blob/main/code/chapter-8/02_segmentation/utils/utils.py#L124)
