### ISSUE TITLE
9.4 机器翻译Transformer， 推理代码有错误

### ISSUE THREAD

**Issue by justinge** [TingsongYu/PyTorch-Tutorial-2nd#25]
Traceback (most recent call last):
  File "/home/justin/Desktop/code/python_project/pytorch-Tutorial-2nd/chapter-9/c_transformer/inference_transformer.py", line 115, in <module>
    main()
  File "/home/justin/Desktop/code/python_project/pytorch-Tutorial-2nd/chapter-9/c_transformer/inference_transformer.py", line 62, in main
    transformer.load_state_dict(checkpoint['model'])
  File "/home/justin/miniconda3/envs/pytorchbook/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Transformer:
        size mismatch for encoder.src_word_emb.weight: copying a param with shape torch.Size([2556, 512]) from checkpoint, the shape in current model is torch.Size([3000, 512]).

**Comment by TingsongYu** [comment]
这个问题提得很好，在inference_transformer.py代码中，对于Transformer的实例化中，词表大小写错了，本应该是src_vocab_len（2552）的，但是写成了trg_vocab_len（3000）。   
但比较奇怪的是，model_acc_train_71_val_50.chkpt 这个模型的encoder词表大小竟然是3000。 我检查了训练代码，并没有发现encoder词表大小是3000。请问你是从哪里获得对应的ckpt的呢？  （我正在重新训练，再获取一下模型权重看看）

**Comment by TingsongYu** [comment]
现在的代码，先训练，再修改inference_transformer.py中的Transformer的实例化为：
```python
    src_vocab_len, trg_vocab_len = len(train_set.vocab_en), len(train_set.vocab_fra)  # 2522, 3000
    transformer = Transformer(
        src_vocab_len,  # 原来是trg....
        trg_vocab_len,
```
1. code/chapter-9/c_transformer/train_transformer.py
2. code/chapter-9/c_transformer/inference_transformer.py

请尝试看看？

**Comment by TingsongYu** [comment]
这是由于训练的时候，设置了-embs_share_weight, 因此 对于encoder的词表大小等于decoder的词表大小，都是3000。所以在推理的时候，需要将encoder设置为decoder的大小，即原来的2552需要变为3000。
```bash
python train_transformer.py -embs_share_weight -proj_share_weight -label_smoothing -b 256 -warmup 128000 -epoch 400
```
