### ISSUE TITLE
在 1.4 中关于 cuDNN 安装验证的问题

### ISSUE THREAD

**Issue by kaiza-hikaru-del** [TingsongYu/PyTorch-Tutorial-2nd#26]
当仅 CUDA Toolkit 安装配置成功后运行 bandwidthTest.exe 和 deviceQuery.exe 就会有 Result=PASS 的输出，不需要 cuDNN 下载好才会出现，因此可能需要别的方式验证 cuDNN 安装成功与否

**Comment by TingsongYu** [comment]
的确，bandwidthTest.exe 和 deviceQuery.exe 只能验证CUDA的安装。cuDNN的验证可以通过pytorch代码验证，已经修改相关说明，谢谢~
