### ISSUE TITLE
vscode对dataloader进行debug未进入源码

### ISSUE THREAD

**Issue by xiongjhang** [TingsongYu/PyTorch-Tutorial-2nd#27]
关于 `3.2 Dataloader` 进行debug查看dataloader工作原理部分的代码，VsCode中debug步入方式貌似和Pycharm不太一样：

相同代码在Pycharm中能步入到torch中关于dataloader的源码部分，但是在vscode中只是遍历了定义数据集中的`__len__`和`__getitem__`方法，无法定位到torch中的源码。

之前一直使用vscode所以没太注意dataloder的源码逻辑debug，请问在vscode中怎么才能debug进入torch中对应部分源码呢？

（google后没发现对应解决方案...）求大佬指点一下 thks :）

**Comment by TingsongYu** [comment]
vscode的debug还没有深入研究，先留个坑，过几周来研究一下vscode的debug

**Comment by xiongjhang** [comment]
已经解决，请参考：
https://stackoverflow.com/questions/53594900/visual-studio-code-python-debugging-how-to-step-into-external-functions-pack
