### ISSUE TITLE
能不能加入triton-server 的教程

### ISSUE THREAD

**Issue by yijinsheng** [TingsongYu/PyTorch-Tutorial-2nd#28]
希望知道怎么把模型转onnx或者trt之后用triton部署

**Comment by TingsongYu** [comment]
这块用得比较少，推荐看Nvidia的[官方文档](https://docs.nvidia.com/deeplearning/triton-inference-server/archives/triton_inference_server_1120/triton-inference-server-guide/docs/index.html)。B站也有对应的讲解视频，可以参考。
