### ISSUE TITLE
PyTorch实用教程（第二版）是基于pytorch2.0的吗？

### ISSUE THREAD

**Issue by A-Pai** [TingsongYu/PyTorch-Tutorial-2nd#4]
非常感谢作者的辛勤工作和慷慨分享，请问：
1、PyTorch实用教程（第二版）是基于pytorch2.0的吗？如果不是，这个教程适用于2.0吗？为何不基于2.0呢？
2、csdn上说“PDF电子版获取方式：公众号回复“PyTorch实用教程””，怎么公众号回复？

**Comment by TingsongYu** [comment]
上篇是基于pytorch 1.12的，中篇会根据项目有特定版本的要求。 教程适用于pytorch2.0的，2.0最大的更新与基础理论知识没有关系，主要涉及底层的实现。基础知识学习用什么版本的ok的，对于项目应用，通常都需要独立的虚拟环境，这块第一章有详细介绍环境的配置。  
在写上篇的时候，pytorch还没有2.0；
PDF的获取可以通过github的 releases下载：https://github.com/TingsongYu/PyTorch-Tutorial-2nd/releases/tag/v1.0.0，或者加入qq群群文件，。 公众号是其他公众号设置的，不是本项目的设置。
