### ISSUE TITLE
7.2 Finetune 模型微调代码中的模型参数冻结

### ISSUE THREAD

**Issue by sunxiuwenO2** [TingsongYu/PyTorch-Tutorial-2nd#7]
code/chapter-7/02_fintune-freeze.py
第137行代码，冻结模型参数，requires_grad 应为 False

**Comment by TingsongYu** [comment]
多谢提醒。
已修改：[chapter-7/02_fintune-freeze.py](https://github.com/TingsongYu/PyTorch-Tutorial-2nd/blob/main/code/chapter-7/02_fintune-freeze.py)
